DELETE FROM savedparts;
DELETE FROM partsmerchants;
DELETE FROM user;
DELETE FROM parts;
DELETE FROM categories;
DELETE FROM merchants;
INSERT INTO user VALUES (1, 'Bobby', 'Joe', 'bobby-joe', 'bobbyjoe@gmail.com', 0, 53589);
INSERT INTO user VALUES (2, 'Chris', 'Franklin', 'frank-chris', 'frank-chris@gmail.com', 0, 53704);
INSERT INTO user VALUES (3, 'Jess', 'Jones', 'jones-jess', 'jones-jess@gmail.com', 0, 53589);
INSERT INTO merchants VALUES (1, 'TestMerchant', 'TestFileLocation.jpg', 'website.com');
INSERT INTO merchants VALUES (2, 'TestMerchantTwo', 'TestFileLocation.jpg', 'websiteTwo.com');
INSERT INTO merchants VALUES (3, 'TestMerchantThree', 'TestFileLocation.jpg', 'websiteThree.com');
INSERT INTO categories VALUES (1, 'Exhaust');
INSERT INTO categories VALUES (2, 'Engine');
INSERT INTO categories VALUES (3, 'Interior');
INSERT INTO parts VALUES (1, 'greatExhaust', '12345', 'its a good exhaust', 'notareallocation', 1);
INSERT INTO parts VALUES (2, 'greatEngine', '54321', 'its a good engine', 'notareallocation', 2);
INSERT INTO parts VALUES (3, 'greatInteriorPart', '23451', 'its a good interior part', 'notareallocation', 3);
INSERT INTO savedparts VALUES (1, 1);
INSERT INTO partsmerchants VALUES (1, 1, 'linktoPart', 'cheap');